"""AIOS Engineering Harness foundation and repository intelligence."""
from __future__ import annotations

from src.aios_engineering.harness.contracts import (
    EvidenceKind,
    HarnessEvidenceExclusion,
    HarnessExtensionPoint,
    HarnessIntelligencePlan,
    HarnessReceipt,
    RepositoryEvidenceRef,
    RepositorySnapshotRef,
)
from src.aios_engineering.harness.errors import (
    HarnessError,
    HarnessFingerprintError,
    HarnessValidationError,
    RepositoryDiscoveryBoundError,
    RepositoryDiscoveryError,
    RepositoryDiscoveryGitError,
)
from src.aios_engineering.harness.discovery import (
    H1_DISCOVERY_POLICY_VERSION,
    MAX_DISCOVERY_ENTRIES,
    MAX_DISCOVERY_STREAM_BYTES,
    MAX_GIT_TREE_RECORD_BYTES,
    RepositoryDiscoveryExclusion,
    RepositoryDiscoveryResult,
    classify_evidence_kind,
    discover_repository_snapshot,
)
from src.aios_engineering.harness.fingerprint import (
    canonical_json_bytes,
    compute_candidate_set_fingerprint,
    compute_plan_fingerprint,
    compute_sha256,
)
from src.aios_engineering.harness.ranking import (
    EXACT_PATH_WEIGHT,
    H2_RANKING_POLICY_VERSION,
    H2_SELECTION_BOUND,
    H2_TASK_RELEVANCE,
    H2_ZERO_RELEVANCE,
    MAX_EXACT_PATH_HINTS,
    MAX_PATH_PREFIX_HINTS,
    MAX_QUERY_TERMS,
    MAX_QUERY_TERM_LENGTH,
    MAX_RELEVANCE_SCORE,
    MAX_SELECTED_EVIDENCE,
    PATH_PREFIX_WEIGHT,
    PREFERRED_KIND_WEIGHT,
    QUERY_TERM_WEIGHT,
    RANKING_SCHEMA_VERSION,
    RepositoryRankingResult,
    TaskRelevanceSpec,
    compute_relevance_spec_fingerprint,
    rank_repository_evidence,
)

__all__ = [
    "EvidenceKind",
    "HarnessEvidenceExclusion",
    "HarnessExtensionPoint",
    "HarnessIntelligencePlan",
    "HarnessReceipt",
    "RepositoryEvidenceRef",
    "RepositorySnapshotRef",
    "HarnessError",
    "HarnessFingerprintError",
    "HarnessValidationError",
    "RepositoryDiscoveryBoundError",
    "RepositoryDiscoveryError",
    "RepositoryDiscoveryGitError",
    "H1_DISCOVERY_POLICY_VERSION",
    "MAX_DISCOVERY_ENTRIES",
    "MAX_DISCOVERY_STREAM_BYTES",
    "MAX_GIT_TREE_RECORD_BYTES",
    "RepositoryDiscoveryExclusion",
    "RepositoryDiscoveryResult",
    "classify_evidence_kind",
    "discover_repository_snapshot",
    "canonical_json_bytes",
    "compute_candidate_set_fingerprint",
    "compute_plan_fingerprint",
    "compute_sha256",
    "EXACT_PATH_WEIGHT",
    "H2_RANKING_POLICY_VERSION",
    "H2_SELECTION_BOUND",
    "H2_TASK_RELEVANCE",
    "H2_ZERO_RELEVANCE",
    "MAX_EXACT_PATH_HINTS",
    "MAX_PATH_PREFIX_HINTS",
    "MAX_QUERY_TERMS",
    "MAX_QUERY_TERM_LENGTH",
    "MAX_RELEVANCE_SCORE",
    "MAX_SELECTED_EVIDENCE",
    "PATH_PREFIX_WEIGHT",
    "PREFERRED_KIND_WEIGHT",
    "QUERY_TERM_WEIGHT",
    "RANKING_SCHEMA_VERSION",
    "RepositoryRankingResult",
    "TaskRelevanceSpec",
    "compute_relevance_spec_fingerprint",
    "rank_repository_evidence",
]
