from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence, Tuple


class SignalProvenance(str, Enum):
    """Provenance tracking for factual vs inferred signals."""
    OBSERVED = "OBSERVED"    # Directly observed from marketplace listing
    DERIVED = "DERIVED"      # Deterministically computed from multiple observations/snapshots
    INFERRED = "INFERRED"    # Generated by semantic/heuristic reasoning (e.g. LLM contentability)
    MISSING = "MISSING"      # Signal was expected but not present in observation


class ScoreCategory(str, Enum):
    """The six canonical V1 winning product intelligence score categories."""
    DEMAND = "DEMAND"
    MOMENTUM = "MOMENTUM"
    COMMERCIAL_ATTRACTIVENESS = "COMMERCIAL_ATTRACTIVENESS"
    TRUST = "TRUST"
    CONTENTABILITY = "CONTENTABILITY"
    COMPETITION_OPPORTUNITY = "COMPETITION_OPPORTUNITY"


class DecisionBand(str, Enum):
    """Advisory decision bands for operator review."""
    RECOMMENDED = "RECOMMENDED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    HOLD = "HOLD"


# Canonical registry of V1 factual marketplace signals to their mandatory category
CANONICAL_FACTUAL_SIGNALS: Dict[str, ScoreCategory] = {
    "sold_volume": ScoreCategory.DEMAND,
    "review_depth": ScoreCategory.DEMAND,
    "sales_velocity": ScoreCategory.MOMENTUM,
    "creator_growth": ScoreCategory.MOMENTUM,
    "commission_rate": ScoreCategory.COMMERCIAL_ATTRACTIVENESS,
    "discount_appeal": ScoreCategory.COMMERCIAL_ATTRACTIVENESS,
    "rating_quality": ScoreCategory.TRUST,
    "market_whitespace": ScoreCategory.COMPETITION_OPPORTUNITY,
    "creator_whitespace": ScoreCategory.COMPETITION_OPPORTUNITY,
}

# Maximum safe scalar length for diagnostic raw value representations
MAX_RAW_VALUE_REPR_LEN = 120

# Forbidden sensitive keywords and structured payload characters in raw_value_repr
FORBIDDEN_RAW_KEYWORDS = (
    "bearer",
    "token",
    "cookie",
    "session",
    "auth",
    "secret",
    "apikey",
    "password",
    "credential",
)
FORBIDDEN_STRUCTURE_CHARS = ("{", "}", "<", ">", "[", "]", ";", "=")


@dataclass(frozen=True)
class SignalEvidence:
    """
    Immutable audit trail for a single observed or derived market fact.
    Enforces scalar bounded diagnostics; strictly forbids credentials, cookies, tokens, or raw payloads.
    """
    signal_name: str
    source_type: str
    observed_at: datetime
    source_url: Optional[str] = None
    collector: str = "default_collector"
    raw_value_repr: Optional[str] = None
    source_reliability: float = 1.0

    def __post_init__(self) -> None:
        if not (0.0 <= self.source_reliability <= 1.0):
            raise ValueError(
                f"source_reliability must be in [0.0, 1.0], got {self.source_reliability}"
            )
        if not self.signal_name:
            raise ValueError("signal_name cannot be empty")
        if not self.source_type:
            raise ValueError("source_type cannot be empty")

        if self.raw_value_repr is not None:
            if len(self.raw_value_repr) > MAX_RAW_VALUE_REPR_LEN:
                raise ValueError(
                    f"raw_value_repr exceeds maximum safe scalar length of {MAX_RAW_VALUE_REPR_LEN} chars, got {len(self.raw_value_repr)}"
                )
            if "\n" in self.raw_value_repr or "\r" in self.raw_value_repr:
                raise ValueError(
                    "raw_value_repr must be a single-line scalar diagnostic, multiline payloads forbidden"
                )

            # Check structured characters (JSON, HTML/XML, assignments)
            for char in FORBIDDEN_STRUCTURE_CHARS:
                if char in self.raw_value_repr:
                    raise ValueError(
                        f"raw_value_repr contains forbidden payload or assignment character {char!r}"
                    )

            # Check sensitive token keywords (word-boundary or substring in lower case)
            raw_lower = self.raw_value_repr.lower()
            for kw in FORBIDDEN_RAW_KEYWORDS:
                if kw in raw_lower:
                    raise ValueError(
                        f"raw_value_repr contains forbidden sensitive or credential keyword: {kw!r}"
                    )

    @classmethod
    def format_scalar(cls, value: Any, unit: str = "") -> str:
        """Utility helper to safely format a scalar diagnostic string."""
        if value is None:
            return "None"
        if isinstance(value, float):
            formatted = f"{value:.2f}" if not value.is_integer() else f"{int(value)}"
        else:
            formatted = str(value)
        return f"{formatted}{unit}" if unit else formatted

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_name": self.signal_name,
            "source_type": self.source_type,
            "source_url": self.source_url,
            "observed_at": self.observed_at.isoformat(),
            "collector": self.collector,
            "raw_value_repr": self.raw_value_repr,
            "source_reliability": self.source_reliability,
        }


@dataclass(frozen=True)
class ProductCandidateSnapshot:
    """
    Immutable observation of a single marketplace listing at a specific point in time.
    Unknown values remain None; never converted to 0.
    """
    candidate_id: str
    platform: str
    url: str
    observed_at: datetime
    title: str
    source_product_id: Optional[str] = None
    collector: str = "discovery_adapter"

    # Descriptive fields
    shop_id: Optional[str] = None
    shop_name: Optional[str] = None
    category: Optional[str] = None
    brand: Optional[str] = None
    model: Optional[str] = None

    # Market / economic fields (nullable when not observed)
    price: Optional[float] = None
    original_price: Optional[float] = None
    discount_percent: Optional[float] = None
    sold_count: Optional[int] = None
    rating: Optional[float] = None
    review_count: Optional[int] = None
    # Canonical unit: percentage points in [0.0, 100.0] (e.g. 15.0 = 15%, 1.0 = 1%)
    affiliate_commission_rate: Optional[float] = None
    estimated_commission_value: Optional[float] = None
    creator_count: Optional[int] = None
    video_count: Optional[int] = None
    similar_listing_count: Optional[int] = None

    # Prior-observation deltas / derived velocity metrics
    sales_velocity: Optional[float] = None
    review_velocity: Optional[float] = None
    creator_velocity: Optional[float] = None
    video_velocity: Optional[float] = None

    def __post_init__(self) -> None:
        if not self.candidate_id:
            raise ValueError("candidate_id cannot be empty")
        if not self.platform:
            raise ValueError("platform cannot be empty")
        if not self.url:
            raise ValueError("url cannot be empty")
        if not self.title:
            raise ValueError("title cannot be empty")

        # Range and non-negativity validations
        if self.price is not None and self.price < 0:
            raise ValueError(f"price cannot be negative, got {self.price}")
        if self.original_price is not None and self.original_price < 0:
            raise ValueError(f"original_price cannot be negative, got {self.original_price}")
        if self.discount_percent is not None and not (0.0 <= self.discount_percent <= 100.0):
            raise ValueError(f"discount_percent must be in [0, 100], got {self.discount_percent}")
        if self.sold_count is not None and self.sold_count < 0:
            raise ValueError(f"sold_count cannot be negative, got {self.sold_count}")
        if self.rating is not None and not (0.0 <= self.rating <= 5.0):
            raise ValueError(f"rating must be in [0.0, 5.0], got {self.rating}")
        if self.review_count is not None and self.review_count < 0:
            raise ValueError(f"review_count cannot be negative, got {self.review_count}")
        if self.affiliate_commission_rate is not None and not (0.0 <= self.affiliate_commission_rate <= 100.0):
            raise ValueError(
                f"affiliate_commission_rate must be in [0.0, 100.0], got {self.affiliate_commission_rate}"
            )
        if self.estimated_commission_value is not None and self.estimated_commission_value < 0:
            raise ValueError(
                f"estimated_commission_value cannot be negative, got {self.estimated_commission_value}"
            )
        if self.creator_count is not None and self.creator_count < 0:
            raise ValueError(f"creator_count cannot be negative, got {self.creator_count}")
        if self.video_count is not None and self.video_count < 0:
            raise ValueError(f"video_count cannot be negative, got {self.video_count}")
        if self.similar_listing_count is not None and self.similar_listing_count < 0:
            raise ValueError(
                f"similar_listing_count cannot be negative, got {self.similar_listing_count}"
            )
        if self.sales_velocity is not None and self.sales_velocity < 0:
            raise ValueError(f"sales_velocity cannot be negative, got {self.sales_velocity}")
        if self.review_velocity is not None and self.review_velocity < 0:
            raise ValueError(f"review_velocity cannot be negative, got {self.review_velocity}")
        if self.creator_velocity is not None and self.creator_velocity < 0:
            raise ValueError(f"creator_velocity cannot be negative, got {self.creator_velocity}")
        if self.video_velocity is not None and self.video_velocity < 0:
            raise ValueError(f"video_velocity cannot be negative, got {self.video_velocity}")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "platform": self.platform,
            "source_product_id": self.source_product_id,
            "url": self.url,
            "observed_at": self.observed_at.isoformat(),
            "collector": self.collector,
            "title": self.title,
            "shop_id": self.shop_id,
            "shop_name": self.shop_name,
            "category": self.category,
            "brand": self.brand,
            "model": self.model,
            "price": self.price,
            "original_price": self.original_price,
            "discount_percent": self.discount_percent,
            "sold_count": self.sold_count,
            "rating": self.rating,
            "review_count": self.review_count,
            "affiliate_commission_rate": self.affiliate_commission_rate,
            "estimated_commission_value": self.estimated_commission_value,
            "creator_count": self.creator_count,
            "video_count": self.video_count,
            "similar_listing_count": self.similar_listing_count,
            "sales_velocity": self.sales_velocity,
            "review_velocity": self.review_velocity,
            "creator_velocity": self.creator_velocity,
            "video_velocity": self.video_velocity,
        }


@dataclass(frozen=True)
class NormalizedSignal:
    """
    A platform-agnostic normalized market signal with score in [0.0, 1.0].
    Enforces canonical signal-name to category pairing and strict category-to-provenance boundaries:
    - Canonical factual signals must match their designated category and forbid INFERRED provenance.
    - Semantic category (CONTENTABILITY) cannot have OBSERVED provenance and cannot use factual signal names.
    """
    name: str
    category: ScoreCategory
    score: float
    provenance: SignalProvenance
    evidence_refs: Tuple[SignalEvidence, ...] = field(default_factory=tuple)
    freshness: float = 1.0
    source_reliability: float = 1.0
    weight: float = 1.0

    def __post_init__(self) -> None:
        if not (0.0 <= self.score <= 1.0):
            raise ValueError(f"score must be in [0.0, 1.0], got {self.score}")
        if not (0.0 <= self.freshness <= 1.0):
            raise ValueError(f"freshness must be in [0.0, 1.0], got {self.freshness}")
        if not (0.0 <= self.source_reliability <= 1.0):
            raise ValueError(
                f"source_reliability must be in [0.0, 1.0], got {self.source_reliability}"
            )
        if self.weight <= 0:
            raise ValueError(f"weight must be strictly positive, got {self.weight}")
        if not self.name:
            raise ValueError("name cannot be empty")

        # 1. Canonical Signal Name to Category Registry Check
        if self.name in CANONICAL_FACTUAL_SIGNALS:
            expected_cat = CANONICAL_FACTUAL_SIGNALS[self.name]
            if self.category != expected_cat:
                raise ValueError(
                    f"Canonical signal {self.name!r} must belong to category {expected_cat.value}, got {self.category.value}"
                )
            if self.provenance == SignalProvenance.INFERRED:
                raise ValueError(
                    f"Canonical factual signal {self.name!r} cannot have INFERRED provenance"
                )

        # 2. Category Provenance Boundary Checks
        if self.category == ScoreCategory.CONTENTABILITY:
            if self.provenance == SignalProvenance.OBSERVED:
                raise ValueError(
                    f"Semantic signal in category {self.category.value} cannot have OBSERVED provenance"
                )
            if self.name in CANONICAL_FACTUAL_SIGNALS:
                raise ValueError(
                    f"Canonical factual signal {self.name!r} cannot be placed in {self.category.value}"
                )
        else:
            if self.provenance == SignalProvenance.INFERRED:
                raise ValueError(
                    f"Factual market signal in category {self.category.value} cannot have INFERRED provenance"
                )

        # 3. MISSING Signal Integrity Check
        if self.provenance == SignalProvenance.MISSING:
            if self.score != 0.0:
                raise ValueError("MISSING signals must have score=0.0")
            if len(self.evidence_refs) > 0:
                raise ValueError("MISSING signals cannot have evidence references")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "category": self.category.value,
            "score": self.score,
            "provenance": self.provenance.value,
            "evidence_refs": [e.to_dict() for e in self.evidence_refs],
            "freshness": self.freshness,
            "source_reliability": self.source_reliability,
            "weight": self.weight,
        }


@dataclass(frozen=True)
class CategoryScore:
    """Breakdown score for one of the 6 canonical categories."""
    category: ScoreCategory
    raw_score: float         # Aggregated signal score in [0.0, 1.0]
    weight: float            # Maximum category points (e.g. 25.0)
    weighted_score: float    # Points earned in this category = raw_score * weight
    coverage: float          # Signal completeness for this category in [0.0, 1.0]
    signals: Tuple[NormalizedSignal, ...] = field(default_factory=tuple)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "category": self.category.value,
            "raw_score": round(self.raw_score, 4),
            "weight": self.weight,
            "weighted_score": round(self.weighted_score, 4),
            "coverage": round(self.coverage, 4),
            "signals": [s.to_dict() for s in self.signals],
        }


@dataclass(frozen=True)
class ConfidenceBreakdown:
    """Deterministic 4-dimensional confidence breakdown."""
    data_completeness: float     # Weight 0.40
    freshness: float             # Weight 0.25
    source_reliability: float    # Weight 0.20
    evidence_coverage: float     # Weight 0.15
    overall_confidence: float    # Weighted combination in [0.0, 1.0]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "data_completeness": round(self.data_completeness, 4),
            "freshness": round(self.freshness, 4),
            "source_reliability": round(self.source_reliability, 4),
            "evidence_coverage": round(self.evidence_coverage, 4),
            "overall_confidence": round(self.overall_confidence, 4),
        }


@dataclass(frozen=True)
class WinningProductScore:
    """
    Complete, reproducible, and explainable winning product intelligence score.
    """
    candidate_id: str
    platform: str
    base_score: float
    confidence: float
    final_score: float
    decision_band: DecisionBand
    category_scores: Dict[ScoreCategory, CategoryScore]
    confidence_breakdown: ConfidenceBreakdown
    key_supporting_signals: Tuple[str, ...]
    missing_or_weak_signals: Tuple[str, ...]
    evidence_references: Tuple[SignalEvidence, ...]
    reason_codes: Tuple[str, ...]
    evaluated_at: datetime

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "platform": self.platform,
            "base_score": round(self.base_score, 4),
            "confidence": round(self.confidence, 4),
            "final_score": round(self.final_score, 4),
            "decision_band": self.decision_band.value,
            "category_scores": {
                k.value: v.to_dict() for k, v in self.category_scores.items()
            },
            "confidence_breakdown": self.confidence_breakdown.to_dict(),
            "key_supporting_signals": list(self.key_supporting_signals),
            "missing_or_weak_signals": list(self.missing_or_weak_signals),
            "evidence_references": [e.to_dict() for e in self.evidence_references],
            "reason_codes": list(self.reason_codes),
            "evaluated_at": self.evaluated_at.isoformat(),
        }
