"""Open Multi-Agent Continuity OS — Canonical Project State, Usage Telemetry & Brain-Neutral Contract (M1 / M1.5 / M2)."""
from __future__ import annotations

from .brain import (
    OPERATION_OUTPUT_TYPE_COMPATIBILITY,
    BrainCapability,
    BrainOutputType,
    BrainRequest,
    BrainResult,
    BrainResultStatus,
    ContextRef,
    OutputContract,
)
from .errors import ContinuityError, ContinuityFreshnessError, ContinuityStateValidationError
from .state import (
    MAX_SERIALIZED_BYTES,
    PHASE_NEXT_OPERATION_MAP,
    PHASES_REQUIRING_TASK_BRANCH_SHA,
    SCHEMA_VERSION,
    ArtifactRef,
    BrainOperation,
    BrainState,
    BranchState,
    ContinuityArtifacts,
    ContinuityPhase,
    ContinuityState,
    ExecutorState,
    FreshnessIssue,
    FreshnessIssueCode,
    FreshnessReport,
    FreshnessStatus,
    NextOperation,
    StateObservation,
    check_freshness,
)
from .usage import (
    BrainUsageRecord,
    EfficiencyMetrics,
    ExecutorAction,
    ExecutorUsageRecord,
    HumanUsage,
    TaskUsageRecord,
    TokenMeasurement,
    UsageSource,
    aggregate_token_ranges,
    calculate_context_efficiency_ratio,
    estimate_tokens_from_bytes,
)

__all__ = [
    "MAX_SERIALIZED_BYTES",
    "OPERATION_OUTPUT_TYPE_COMPATIBILITY",
    "PHASE_NEXT_OPERATION_MAP",
    "PHASES_REQUIRING_TASK_BRANCH_SHA",
    "SCHEMA_VERSION",
    "ArtifactRef",
    "BrainCapability",
    "BrainOperation",
    "BrainOutputType",
    "BrainRequest",
    "BrainResult",
    "BrainResultStatus",
    "BrainState",
    "BrainUsageRecord",
    "BranchState",
    "ContextRef",
    "ContinuityArtifacts",
    "ContinuityError",
    "ContinuityFreshnessError",
    "ContinuityPhase",
    "ContinuityState",
    "ContinuityStateValidationError",
    "EfficiencyMetrics",
    "ExecutorAction",
    "ExecutorState",
    "ExecutorUsageRecord",
    "FreshnessIssue",
    "FreshnessIssueCode",
    "FreshnessReport",
    "FreshnessStatus",
    "HumanUsage",
    "NextOperation",
    "OutputContract",
    "StateObservation",
    "TaskUsageRecord",
    "TokenMeasurement",
    "UsageSource",
    "aggregate_token_ranges",
    "calculate_context_efficiency_ratio",
    "check_freshness",
    "estimate_tokens_from_bytes",
]
